module.exports = {
  ores: [
    "oreCopper",
    "oreLead",
    "oreScrap",
    "oreCoal",
    "oreTitanium",
    "oreThorium",
  ],
  blocks: {
    crafting: [
      "siliconSmelter",
      "siliconCrucible",
      "kiln",
      "graphitePress",
      "plastaniumCompressor",
      "multiPress",
      "phaseWeaver",
      "surgeSmelter",
      "pyratiteMixer",
      "blastMixer",
      "cryofluidMixer",
      "melter",
      "separator",
      "disassembler",
      "sporePress",
      "pulverizer",
      "incinerator",
      "coalCentrifuge",
    ],
    sandbox: [
      "powerSource",
      "powerVoid",
      "itemSource",
      "itemVoid",
      "liquidSource",
      "liquidVoid",
      "illuminator",
    ],
    defense: [
      "copperWall",
      "copperWallLarge",
      "titaniumWall",
      "titaniumWallLarge",
      "plastaniumWall",
      "plastaniumWallLarge",
      "thoriumWall",
      "thoriumWallLarge",
      "door",
      "doorLarge",
      "phaseWall",
      "phaseWallLarge",
      "surgeWall",
      "surgeWallLarge",
      "mender",
      "mendProjector",
      "overdriveProjector",
      "overdriveDome",
      "horseProjector",
      "shockMine",
      "scrapWall",
      "scrapWallLarge",
      "scrapWallHuge",
      "scrapWallGigantic",
      "thruster",
    ],
    transport: [
      "conveyor",
      "titaniumConveyor",
      "plastaniumConveyor",
      "armoardConveyor",
      "distributor",
      "junction",
      "itemBridge",
      "phaseConveyor",
      "sorter",
      "invertedSorter",
      "router",
      "overflowGate",
      "underflowGate",
      "massDriver",
      "payloadConveyor",
      "payloadRouter",
    ],
    liquid: [
      "mechanicalPump",
      "rotaryPump",
      "thermalPump",
      "conduit",
      "pulseConduit",
      "platedConduit",
      "liquidRouter",
      "liquidTank",
      "liquidJunction",
      "bridgeConduit",
      "phaseConduit",
    ],
    power: [
      "combustionGenerator",
      "thermalGenerator",
      "turbineGenerator",
      "differentialGenerator",
      "rtgGenerator",
      "solarPanel",
      "largeSolarPanel",
      "thoriumReactor",
      "impactReactor",
      "battery",
      "batteryLarge",
      "powerNode",
      "powerNodeLarge",
      "surgeTower",
      "diode",
    ],
    production: [
      "mechanicalDrill",
      "pneumaticDrill",
      "laserDrill",
      "blastDrill",
      "waterExtractor",
      "oilExtractor",
      "cultivator",
    ],
    storage: [
      "coreShard",
      "coreFoundation",
      "coreNucleus",
      "vault",
      "container",
      "unloader",
    ],
    turrets: [
      "duo",
      "scatter",
      "scorch",
      "hail",
      "arc",
      "wave",
      "lancer",
      "swarmer",
      "salvo",
      "fuse",
      "ripple",
      "cyclone",
      "spectre",
      "meltdown",
      "segment",
      "parallax",
    ],
    units: [
      "commandCenter",
      "groundFactory",
      "airFactory",
      "navalFactory",
      "additiveReconstructor",
      "multiplicativeReconstructor",
      "exponentialReconstructor",
      "tetrativeReconstructor",
      "repairPoint",
      "resupplyPoint",
    ],
    logic: [
      "message",
      "switchBlock",
      "microProcessor",
      "logicProcessor",
      "hyperProcessor",
      "logicDisplay",
      "memoryCell",
    ],
    campaign: ["launchPad", "launchPadLarge"],
    experimental: ["blockForge", "blockLoader", "blockUnloader"],
  },
  items: {
    83886080:'copper',
    83886081:'lead',
    83886082:'meta glass',
    83886083:'graphite',
    83886084:'sand',
    83886085:'coal',
    83886086:'titanium',
    83886087:'thorium',
    83886088:'scrap',
    83886089:'silicon',
    83886090:'plastanium',
    83886091:'phase Fabric',
    83886092:'surgealloy',
    83886093:'Spore pod',
    83886094:'blastCompound',
    83886095:'payatite',
  },
  liquids: {
    84148224:'water',
    84148225:'slag',
    84148226:'oil',
    84148227:'cryofluid'
}
};
